apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-backend
  namespace: default-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: default-backend
  template:
    metadata:
      labels:
        app: default-backend
    spec:
      containers:
      - name: default-backend
        image: ghcr.io/seanconroy2021/sconroy-website@sha256:5b404b099fd1c01b4d55dddcc8871807d6c34248ff00f1d0a93673a07999c763
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
