apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-backend
  namespace: default-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: default-backend
  template:
    metadata:
      labels:
        app: default-backend
    spec:
      containers:
      - name: default-backend
        image: ghcr.io/seanconroy2021/sconroy-website@sha256:c46bb7cbc806f7801611dd328a791ba3b308dce6f8ebfec055e8cefc765c1f82
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
