apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-backend
  namespace: default-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: default-backend
  template:
    metadata:
      labels:
        app: default-backend
    spec:
      containers:
      - name: default-backend
        image: ghcr.io/seanconroy2021/sconroy-website@sha256:116e60460dd92695e71bde0c63420f20b9c65a0dafb0ea1b9ce5fa07af2cf668
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
