apiVersion: v1
kind: Service
metadata:
  name: default-backend
  namespace: default-backend
spec:
  selector:
    app: default-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
