apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: sconroy-website-rpa
  namespace: rhtap-releng-tenant
spec:
  applications:
    - sconroy-website
  origin: rh-ee-sconroy-tenant
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/konflux-ci/release-service-catalog.git
        - name: revision
          value: development
        - name: pathInRepo
          value: pipelines/managed/push-to-external-registry
  policy: mvp-policy
  data:
    mapping:
      components:
        - name: sconroy-website
          repository: "quay.io/rh-ee-sconroy/sconroy-website"
          tags: 
            - latest
          source:
            git:
              url: https://github.com/seanconroy2021/sconroy-website
