name: Mirror to Gitea (via Tailscale)

on:
  push:
    branches:
      - main  # Adjust if needed

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Start Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history is cloned

      - name: Push to Gitea (via Tailscale)
        env:
          GITEA_USERNAME: "sconroy"  # Your Gitea username
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          GITEA_URL: "https://gitea.tail50d51b.ts.net/sconroy/sconroy-website.git"
        run: |
          git remote add gitea "https://${GITEA_USERNAME}:${GITEA_TOKEN}@gitea.tail50d51b.ts.net/sconroy/sconroy-website.git"
          git push --mirror gitea
